### PR TITLE
Fix number version in README 

### PR DESCRIPTION
**Pull request by chripalombella**
Hi @DavidePastore,
i edited the README.md, with the correct number of version.

### CODE REVIEW

**Comment by DavidePastore** [comment]
Hi @chripalombella, thanks for you PR! [Can you please change the target branch of it to 7.x](https://stackoverflow.com/questions/9135913/merge-pull-request-to-a-different-branch-than-default-in-github)? Thanks 😄

**Comment by chripalombella** [comment]
Yes!

**Comment by DavidePastore** [comment]
Thanks @chripalombella!

**Comment by chripalombella** [comment]
You're welcome @DavidePastore !

**Pull request merged**
